apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: photoapp 
  namespace: onedev-managed
spec:
  interval: 5m
  path: ./photoapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: onedev-monorepo
    namespace: onedev-managed
  targetNamespace: photoapp
