apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photoapp-wavl-lab-net-cert
  namespace: photoapp
spec:
  secretName: photoapp-wavl-lab-net-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
  - photoapp.wavl-lab.net
